[[INCLUDE component=Favicon]]
[[INCLUDE component=AdminxPages]]

window.addEventListener('load', function(e) {
    var ap = new AdminxPages();
    document.getElementById('container').appendChild(ap.dom);
}, true);

setFavicon('data:image/x-icon;base64,AAABAAEAEBAQAAAAAAAoAQAAFgAAACgAAAAQAAAAIAAAAAEABAAAAAAAgAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAA7e3tAP+EAAD///8A4ODgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiIiIiIiIiACMzMzMzMzIAIzRERERDMgAjMzMzMzMyACM0RENEQzIAIzMzM0RDMgAjNERDREMyACMzMzMzMzIAIzRERERDMgAjNBEREUMyACM0EREiIiIAIzQRESMzMgAjNBERIzMgACM0REQjMgAAIzMzMyMgAAAiIiIiIgAACAAQAAgAEAAIABAACAAQAAgAEAAIABAACAAQAAgAEAAIABAACAAQAAgAEAAIABAACAAwAAgAcAAIAPAACAHwAA');