<?php

	/**
	 * # CAUTION #
	 *
	 * Autogenerated code. Any changes in this file will be lost.
	 * To add extra behaviour, please, edit the extended class (extended.class.php)
	 *
	*/

	class NotesEntry_auto {

		public static $fields = array (
  'Notes' => 
  array (
    'type' => 'Notes',
    'native' => false,
  ),
  'Author' => 
  array (
    'type' => 'SystemUser',
    'native' => false,
  ),
  'Title' => 
  array (
    'type' => 'Label',
    'native' => false,
  ),
  'Content' => 
  array (
    'type' => 'SimpleText',
    'native' => false,
  ),
  'Creation' => 
  array (
    'type' => 'Number',
    'native' => true,
  ),
  'Publication' => 
  array (
    'type' => 'Number',
    'native' => true,
  ),
);

		protected static $data = array();

		protected $id;
		protected $timestamp;
		protected $operation;
		public $row;

		public function __construct(&$row) {
			$this->id = $row['id'];
			$this->timestamp = $row['__timestamp__'];
			$this->operation = $row['__operation__'];
			$this->row = $row;
		}

		public function RAW($field) {
			if (array_key_exists($field, $this->row)) {
				return $this->row[$field];
			}
			return null;
		}

		public static function PREFETCH($field, $collection) {
			$IDs = array();
			foreach ($collection as $item) {
				$IDs[] = $item->RAW($field);
			}
			$IDs = array_unique($IDs);
			if (count($IDs)) {
				$implode = implode(',', $IDs);
				return self::SELECT(" Id IN ($implode) ");
			}
			return array();
		}

		public static function SELECT($where=null) {
			$db = Database::getInstance();

			$sql = "SELECT * FROM `NotesEntry`";
			if ($where !== null)
				$sql .= " WHERE ".$where;

			$select = array();
			$result = $db->sql($sql);
			while ($result && $row=mysql_fetch_assoc($result)) {
				$id = $row['id'];
				if (!array_key_exists($id, self::$data))
					self::$data[$id] = new NotesEntry($row);
				$select[] = &self::$data[$id];
			}
			return $select;
		}
		
		public static function INSERT() {
			$db = Database::getInstance();
			$sql = "INSERT INTO `NotesEntry` (`id`, `__timestamp__`, `__operation__`) VALUES (NULL, ".time().", 'INSERT')";
			$result = $db->sql($sql);
			$id = mysql_insert_id();
			return self::ROW($id);
		}

		public static function ROW($id) {
			$id = intval($id);
			if (array_key_exists($id, self::$data)) {
				return self::$data[$id];
			} else {
				$db = Database::getInstance();
				$rows = self::SELECT("id='".mysql_real_escape_string($id)."'");
				if (count($rows)) {
					return $rows[0];
				} else {
					return null;
				}
			}
		}

		public function DELETE($physical=true) {
			$db = Database::getInstance();
			if ($physical) {
				$sql = "DELETE FROM `NotesEntry` WHERE id='".$this->id."'";
				unset(self::$data[$this->id]);
			} else {
				$sql = "UPDATE `NotesEntry` SET `__timestamp__` = ".time().", `__operation__` = 'DELETE' WHERE `id`='".$this->id."'";
			}
			$db->sql($sql);
		}

		/* Deprecated */
		public final function getId() {
			return intval($this->id);
		}

		public final function ID() {
			return intval($this->id);
		}

		public final function TIMESTAMP() {
			return intval($this->timestamp);
		}

		public final function OPERATION() {
			return $this->operation;
		}

		public final function getClassName() {
			return 'NotesEntry';
		}

		public function toString() {
			return "NotesEntry[{$this->id}]";
		}

		// Setters and Getters

		public function setNotes($value) {
			if (is_object($value) && $value->getClassName() == 'Notes') {
				$id = $value->getId();
				$db = Database::getInstance();
				$sql = "UPDATE `NotesEntry` SET `Notes`='".$id."',	`__timestamp__` = ".time()." WHERE `id`='".$this->id."'";
				$db->sql($sql);
				$this->row['Notes'] = $id;
			} else if ($value === null) {
				$db = Database::getInstance();
				$sql = "UPDATE `NotesEntry` SET `Notes`='0', `__timestamp__` = ".time()." WHERE `id`='".$this->id."'";
				$db->sql($sql);
				$this->row['Notes'] = 0;
			}
		}

		public function getNotes() {
			if ($this->row['Notes'] == 0) {
				return null;
			} else {
				return Notes::ROW($this->row['Notes']);
			}
		}

		public function setAuthor($value) {
			if (is_object($value) && $value->getClassName() == 'SystemUser') {
				$id = $value->getId();
				$db = Database::getInstance();
				$sql = "UPDATE `NotesEntry` SET `Author`='".$id."',	`__timestamp__` = ".time()." WHERE `id`='".$this->id."'";
				$db->sql($sql);
				$this->row['Author'] = $id;
			} else if ($value === null) {
				$db = Database::getInstance();
				$sql = "UPDATE `NotesEntry` SET `Author`='0', `__timestamp__` = ".time()." WHERE `id`='".$this->id."'";
				$db->sql($sql);
				$this->row['Author'] = 0;
			}
		}

		public function getAuthor() {
			if ($this->row['Author'] == 0) {
				return null;
			} else {
				return SystemUser::ROW($this->row['Author']);
			}
		}

		public function setTitle($value) {
			if (is_object($value) && $value->getClassName() == 'Label') {
				$id = $value->getId();
				$db = Database::getInstance();
				$sql = "UPDATE `NotesEntry` SET `Title`='".$id."',	`__timestamp__` = ".time()." WHERE `id`='".$this->id."'";
				$db->sql($sql);
				$this->row['Title'] = $id;
			} else if ($value === null) {
				$db = Database::getInstance();
				$sql = "UPDATE `NotesEntry` SET `Title`='0', `__timestamp__` = ".time()." WHERE `id`='".$this->id."'";
				$db->sql($sql);
				$this->row['Title'] = 0;
			}
		}

		public function getTitle() {
			if ($this->row['Title'] == 0) {
				return null;
			} else {
				return Label::ROW($this->row['Title']);
			}
		}

		public function setContent($value) {
			if (is_object($value) && $value->getClassName() == 'SimpleText') {
				$id = $value->getId();
				$db = Database::getInstance();
				$sql = "UPDATE `NotesEntry` SET `Content`='".$id."',	`__timestamp__` = ".time()." WHERE `id`='".$this->id."'";
				$db->sql($sql);
				$this->row['Content'] = $id;
			} else if ($value === null) {
				$db = Database::getInstance();
				$sql = "UPDATE `NotesEntry` SET `Content`='0', `__timestamp__` = ".time()." WHERE `id`='".$this->id."'";
				$db->sql($sql);
				$this->row['Content'] = 0;
			}
		}

		public function getContent() {
			if ($this->row['Content'] == 0) {
				return null;
			} else {
				return SimpleText::ROW($this->row['Content']);
			}
		}
public function setCreation($value) { $value = str_replace(',', '.', $value); $this->row['Creation'] = $value; $value = mysql_real_escape_string($value); $timestamp = time(); $sql = "UPDATE `NotesEntry` SET `Creation`='$value', `__timestamp__` = $timestamp, `__operation__` = 'UPDATE'  WHERE `id`='{$this->id}'"; Database::getInstance()->sql($sql); } public function getCreation() { $value = $this->row['Creation']; settype($value, 'float'); return $value; }

public function setPublication($value) { $value = str_replace(',', '.', $value); $this->row['Publication'] = $value; $value = mysql_real_escape_string($value); $timestamp = time(); $sql = "UPDATE `NotesEntry` SET `Publication`='$value', `__timestamp__` = $timestamp, `__operation__` = 'UPDATE'  WHERE `id`='{$this->id}'"; Database::getInstance()->sql($sql); } public function getPublication() { $value = $this->row['Publication']; settype($value, 'float'); return $value; }


	}
