<?php

	/**
	 * # CAUTION #
	 *
	 * Autogenerated code. Any changes in this file will be lost.
	 * To add extra behaviour, please, edit the extended class (extended.class.php)
	 *
	*/

	class BlogPostTags_auto {

		public static $fields = array (
  'Post' => 
  array (
    'type' => 'BlogPost',
    'native' => false,
  ),
  'Tag' => 
  array (
    'type' => 'BlogTag',
    'native' => false,
  ),
);

		protected static $data = array();

		protected $id;
		protected $timestamp;
		protected $operation;
		public $row;

		public function __construct(&$row) {
			$this->id = $row['id'];
			$this->timestamp = $row['__timestamp__'];
			$this->operation = $row['__operation__'];
			$this->row = $row;
		}

		public function RAW($field) {
			if (array_key_exists($field, $this->row)) {
				return $this->row[$field];
			}
			return null;
		}

		public static function PREFETCH($field, $collection) {
			$IDs = array();
			foreach ($collection as $item) {
				$IDs[] = $item->RAW($field);
			}
			$IDs = array_unique($IDs);
			if (count($IDs)) {
				$implode = implode(',', $IDs);
				return self::SELECT(" Id IN ($implode) ");
			}
			return array();
		}

		public static function SELECT($where=null) {
			$db = Database::getInstance();

			$sql = "SELECT * FROM `BlogPostTags`";
			if ($where !== null)
				$sql .= " WHERE ".$where;

			$select = array();
			$result = $db->sql($sql);
			while ($result && $row=mysql_fetch_assoc($result)) {
				$id = $row['id'];
				if (!array_key_exists($id, self::$data))
					self::$data[$id] = new BlogPostTags($row);
				$select[] = &self::$data[$id];
			}
			return $select;
		}
		
		public static function INSERT() {
			$db = Database::getInstance();
			$sql = "INSERT INTO `BlogPostTags` (`id`, `__timestamp__`, `__operation__`) VALUES (NULL, ".time().", 'INSERT')";
			$result = $db->sql($sql);
			$id = mysql_insert_id();
			return self::ROW($id);
		}

		public static function ROW($id) {
			$id = intval($id);
			if (array_key_exists($id, self::$data)) {
				return self::$data[$id];
			} else {
				$db = Database::getInstance();
				$rows = self::SELECT("id='".mysql_real_escape_string($id)."'");
				if (count($rows)) {
					return $rows[0];
				} else {
					return null;
				}
			}
		}

		public function DELETE($physical=true) {
			$db = Database::getInstance();
			if ($physical) {
				$sql = "DELETE FROM `BlogPostTags` WHERE id='".$this->id."'";
				unset(self::$data[$this->id]);
			} else {
				$sql = "UPDATE `BlogPostTags` SET `__timestamp__` = ".time().", `__operation__` = 'DELETE' WHERE `id`='".$this->id."'";
			}
			$db->sql($sql);
		}

		/* Deprecated */
		public final function getId() {
			return intval($this->id);
		}

		public final function ID() {
			return intval($this->id);
		}

		public final function TIMESTAMP() {
			return intval($this->timestamp);
		}

		public final function OPERATION() {
			return $this->operation;
		}

		public final function getClassName() {
			return 'BlogPostTags';
		}

		public function toString() {
			return "BlogPostTags[{$this->id}]";
		}

		// Setters and Getters

		public function setPost($value) {
			if (is_object($value) && $value->getClassName() == 'BlogPost') {
				$id = $value->getId();
				$db = Database::getInstance();
				$sql = "UPDATE `BlogPostTags` SET `Post`='".$id."',	`__timestamp__` = ".time()." WHERE `id`='".$this->id."'";
				$db->sql($sql);
				$this->row['Post'] = $id;
			} else if ($value === null) {
				$db = Database::getInstance();
				$sql = "UPDATE `BlogPostTags` SET `Post`='0', `__timestamp__` = ".time()." WHERE `id`='".$this->id."'";
				$db->sql($sql);
				$this->row['Post'] = 0;
			}
		}

		public function getPost() {
			if ($this->row['Post'] == 0) {
				return null;
			} else {
				return BlogPost::ROW($this->row['Post']);
			}
		}

		public function setTag($value) {
			if (is_object($value) && $value->getClassName() == 'BlogTag') {
				$id = $value->getId();
				$db = Database::getInstance();
				$sql = "UPDATE `BlogPostTags` SET `Tag`='".$id."',	`__timestamp__` = ".time()." WHERE `id`='".$this->id."'";
				$db->sql($sql);
				$this->row['Tag'] = $id;
			} else if ($value === null) {
				$db = Database::getInstance();
				$sql = "UPDATE `BlogPostTags` SET `Tag`='0', `__timestamp__` = ".time()." WHERE `id`='".$this->id."'";
				$db->sql($sql);
				$this->row['Tag'] = 0;
			}
		}

		public function getTag() {
			if ($this->row['Tag'] == 0) {
				return null;
			} else {
				return BlogTag::ROW($this->row['Tag']);
			}
		}

	}
