<?php

	/**
	 * # CAUTION #
	 *
	 * Autogenerated code. Any changes in this file will be lost.
	 * To add extra behaviour, please, edit the extended class (extended.class.php)
	 *
	*/

	class GraphicSlideshowItem_auto {

		public static $fields = array (
  'Slideshow' => 
  array (
    'type' => 'GraphicSlideshow',
    'native' => false,
  ),
  'Order' => 
  array (
    'type' => 'Number',
    'native' => true,
  ),
  'Background' => 
  array (
    'type' => 'Image',
    'native' => false,
  ),
  'Title' => 
  array (
    'type' => 'Label',
    'native' => false,
  ),
  'Text' => 
  array (
    'type' => 'SimpleText',
    'native' => false,
  ),
  'Enabled' => 
  array (
    'type' => 'Number',
    'native' => true,
  ),
);

		protected static $data = array();

		protected $id;
		protected $timestamp;
		protected $operation;
		public $row;

		public function __construct(&$row) {
			$this->id = $row['id'];
			$this->timestamp = $row['__timestamp__'];
			$this->operation = $row['__operation__'];
			$this->row = $row;
		}

		public function RAW($field) {
			if (array_key_exists($field, $this->row)) {
				return $this->row[$field];
			}
			return null;
		}

		public static function PREFETCH($field, $collection) {
			$IDs = array();
			foreach ($collection as $item) {
				$IDs[] = $item->RAW($field);
			}
			$IDs = array_unique($IDs);
			if (count($IDs)) {
				$implode = implode(',', $IDs);
				return self::SELECT(" Id IN ($implode) ");
			}
			return array();
		}

		public static function SELECT($where=null) {
			$db = Database::getInstance();

			$sql = "SELECT * FROM `GraphicSlideshowItem`";
			if ($where !== null)
				$sql .= " WHERE ".$where;

			$select = array();
			$result = $db->sql($sql);
			while ($result && $row=mysql_fetch_assoc($result)) {
				$id = $row['id'];
				if (!array_key_exists($id, self::$data))
					self::$data[$id] = new GraphicSlideshowItem($row);
				$select[] = &self::$data[$id];
			}
			return $select;
		}
		
		public static function INSERT() {
			$db = Database::getInstance();
			$sql = "INSERT INTO `GraphicSlideshowItem` (`id`, `__timestamp__`, `__operation__`) VALUES (NULL, ".time().", 'INSERT')";
			$result = $db->sql($sql);
			$id = mysql_insert_id();
			return self::ROW($id);
		}

		public static function ROW($id) {
			$id = intval($id);
			if (array_key_exists($id, self::$data)) {
				return self::$data[$id];
			} else {
				$db = Database::getInstance();
				$rows = self::SELECT("id='".mysql_real_escape_string($id)."'");
				if (count($rows)) {
					return $rows[0];
				} else {
					return null;
				}
			}
		}

		public function DELETE($physical=true) {
			$db = Database::getInstance();
			if ($physical) {
				$sql = "DELETE FROM `GraphicSlideshowItem` WHERE id='".$this->id."'";
				unset(self::$data[$this->id]);
			} else {
				$sql = "UPDATE `GraphicSlideshowItem` SET `__timestamp__` = ".time().", `__operation__` = 'DELETE' WHERE `id`='".$this->id."'";
			}
			$db->sql($sql);
		}

		/* Deprecated */
		public final function getId() {
			return intval($this->id);
		}

		public final function ID() {
			return intval($this->id);
		}

		public final function TIMESTAMP() {
			return intval($this->timestamp);
		}

		public final function OPERATION() {
			return $this->operation;
		}

		public final function getClassName() {
			return 'GraphicSlideshowItem';
		}

		public function toString() {
			return "GraphicSlideshowItem[{$this->id}]";
		}

		// Setters and Getters

		public function setSlideshow($value) {
			if (is_object($value) && $value->getClassName() == 'GraphicSlideshow') {
				$id = $value->getId();
				$db = Database::getInstance();
				$sql = "UPDATE `GraphicSlideshowItem` SET `Slideshow`='".$id."',	`__timestamp__` = ".time()." WHERE `id`='".$this->id."'";
				$db->sql($sql);
				$this->row['Slideshow'] = $id;
			} else if ($value === null) {
				$db = Database::getInstance();
				$sql = "UPDATE `GraphicSlideshowItem` SET `Slideshow`='0', `__timestamp__` = ".time()." WHERE `id`='".$this->id."'";
				$db->sql($sql);
				$this->row['Slideshow'] = 0;
			}
		}

		public function getSlideshow() {
			if ($this->row['Slideshow'] == 0) {
				return null;
			} else {
				return GraphicSlideshow::ROW($this->row['Slideshow']);
			}
		}
public function setOrder($value) { $value = str_replace(',', '.', $value); $this->row['Order'] = $value; $value = mysql_real_escape_string($value); $timestamp = time(); $sql = "UPDATE `GraphicSlideshowItem` SET `Order`='$value', `__timestamp__` = $timestamp, `__operation__` = 'UPDATE'  WHERE `id`='{$this->id}'"; Database::getInstance()->sql($sql); } public function getOrder() { $value = $this->row['Order']; settype($value, 'float'); return $value; }


		public function setBackground($value) {
			if (is_object($value) && $value->getClassName() == 'Image') {
				$id = $value->getId();
				$db = Database::getInstance();
				$sql = "UPDATE `GraphicSlideshowItem` SET `Background`='".$id."',	`__timestamp__` = ".time()." WHERE `id`='".$this->id."'";
				$db->sql($sql);
				$this->row['Background'] = $id;
			} else if ($value === null) {
				$db = Database::getInstance();
				$sql = "UPDATE `GraphicSlideshowItem` SET `Background`='0', `__timestamp__` = ".time()." WHERE `id`='".$this->id."'";
				$db->sql($sql);
				$this->row['Background'] = 0;
			}
		}

		public function getBackground() {
			if ($this->row['Background'] == 0) {
				return null;
			} else {
				return Image::ROW($this->row['Background']);
			}
		}

		public function setTitle($value) {
			if (is_object($value) && $value->getClassName() == 'Label') {
				$id = $value->getId();
				$db = Database::getInstance();
				$sql = "UPDATE `GraphicSlideshowItem` SET `Title`='".$id."',	`__timestamp__` = ".time()." WHERE `id`='".$this->id."'";
				$db->sql($sql);
				$this->row['Title'] = $id;
			} else if ($value === null) {
				$db = Database::getInstance();
				$sql = "UPDATE `GraphicSlideshowItem` SET `Title`='0', `__timestamp__` = ".time()." WHERE `id`='".$this->id."'";
				$db->sql($sql);
				$this->row['Title'] = 0;
			}
		}

		public function getTitle() {
			if ($this->row['Title'] == 0) {
				return null;
			} else {
				return Label::ROW($this->row['Title']);
			}
		}

		public function setText($value) {
			if (is_object($value) && $value->getClassName() == 'SimpleText') {
				$id = $value->getId();
				$db = Database::getInstance();
				$sql = "UPDATE `GraphicSlideshowItem` SET `Text`='".$id."',	`__timestamp__` = ".time()." WHERE `id`='".$this->id."'";
				$db->sql($sql);
				$this->row['Text'] = $id;
			} else if ($value === null) {
				$db = Database::getInstance();
				$sql = "UPDATE `GraphicSlideshowItem` SET `Text`='0', `__timestamp__` = ".time()." WHERE `id`='".$this->id."'";
				$db->sql($sql);
				$this->row['Text'] = 0;
			}
		}

		public function getText() {
			if ($this->row['Text'] == 0) {
				return null;
			} else {
				return SimpleText::ROW($this->row['Text']);
			}
		}
public function setEnabled($value) { $value = str_replace(',', '.', $value); $this->row['Enabled'] = $value; $value = mysql_real_escape_string($value); $timestamp = time(); $sql = "UPDATE `GraphicSlideshowItem` SET `Enabled`='$value', `__timestamp__` = $timestamp, `__operation__` = 'UPDATE'  WHERE `id`='{$this->id}'"; Database::getInstance()->sql($sql); } public function getEnabled() { $value = $this->row['Enabled']; settype($value, 'float'); return $value; }


	}
