<?php

	/**
	 * # CAUTION #
	 *
	 * Autogenerated code. Any changes in this file will be lost.
	 * To add extra behaviour, please, edit the extended class (extended.class.php)
	 *
	*/

	class BlogPost_auto {

		public static $fields = array (
  'Blog' => 
  array (
    'type' => 'Blog',
    'native' => false,
  ),
  'Title' => 
  array (
    'type' => 'Text',
    'native' => true,
  ),
  'Description' => 
  array (
    'type' => 'Text',
    'native' => true,
  ),
  'Content' => 
  array (
    'type' => 'Document',
    'native' => false,
  ),
  'Comments' => 
  array (
    'type' => 'Comment',
    'native' => false,
  ),
  'TimeCreation' => 
  array (
    'type' => 'Number',
    'native' => true,
  ),
  'TimePublished' => 
  array (
    'type' => 'Number',
    'native' => true,
  ),
  'Options' => 
  array (
    'type' => 'Text',
    'native' => true,
  ),
  'Url' => 
  array (
    'type' => 'Text',
    'native' => true,
  ),
  'Author' => 
  array (
    'type' => 'SystemUser',
    'native' => false,
  ),
);

		protected static $data = array();

		protected $id;
		protected $timestamp;
		protected $operation;
		public $row;

		public function __construct(&$row) {
			$this->id = $row['id'];
			$this->timestamp = $row['__timestamp__'];
			$this->operation = $row['__operation__'];
			$this->row = $row;
		}

		public function RAW($field) {
			if (array_key_exists($field, $this->row)) {
				return $this->row[$field];
			}
			return null;
		}

		public static function PREFETCH($field, $collection) {
			$IDs = array();
			foreach ($collection as $item) {
				$IDs[] = $item->RAW($field);
			}
			$IDs = array_unique($IDs);
			if (count($IDs)) {
				$implode = implode(',', $IDs);
				return self::SELECT(" Id IN ($implode) ");
			}
			return array();
		}

		public static function SELECT($where=null) {
			$db = Database::getInstance();

			$sql = "SELECT * FROM `BlogPost`";
			if ($where !== null)
				$sql .= " WHERE ".$where;

			$select = array();
			$result = $db->sql($sql);
			while ($result && $row=mysql_fetch_assoc($result)) {
				$id = $row['id'];
				if (!array_key_exists($id, self::$data))
					self::$data[$id] = new BlogPost($row);
				$select[] = &self::$data[$id];
			}
			return $select;
		}
		
		public static function INSERT() {
			$db = Database::getInstance();
			$sql = "INSERT INTO `BlogPost` (`id`, `__timestamp__`, `__operation__`) VALUES (NULL, ".time().", 'INSERT')";
			$result = $db->sql($sql);
			$id = mysql_insert_id();
			return self::ROW($id);
		}

		public static function ROW($id) {
			$id = intval($id);
			if (array_key_exists($id, self::$data)) {
				return self::$data[$id];
			} else {
				$db = Database::getInstance();
				$rows = self::SELECT("id='".mysql_real_escape_string($id)."'");
				if (count($rows)) {
					return $rows[0];
				} else {
					return null;
				}
			}
		}

		public function DELETE($physical=true) {
			$db = Database::getInstance();
			if ($physical) {
				$sql = "DELETE FROM `BlogPost` WHERE id='".$this->id."'";
				unset(self::$data[$this->id]);
			} else {
				$sql = "UPDATE `BlogPost` SET `__timestamp__` = ".time().", `__operation__` = 'DELETE' WHERE `id`='".$this->id."'";
			}
			$db->sql($sql);
		}

		/* Deprecated */
		public final function getId() {
			return intval($this->id);
		}

		public final function ID() {
			return intval($this->id);
		}

		public final function TIMESTAMP() {
			return intval($this->timestamp);
		}

		public final function OPERATION() {
			return $this->operation;
		}

		public final function getClassName() {
			return 'BlogPost';
		}

		public function toString() {
			return "BlogPost[{$this->id}]";
		}

		// Setters and Getters

		public function setBlog($value) {
			if (is_object($value) && $value->getClassName() == 'Blog') {
				$id = $value->getId();
				$db = Database::getInstance();
				$sql = "UPDATE `BlogPost` SET `Blog`='".$id."',	`__timestamp__` = ".time()." WHERE `id`='".$this->id."'";
				$db->sql($sql);
				$this->row['Blog'] = $id;
			} else if ($value === null) {
				$db = Database::getInstance();
				$sql = "UPDATE `BlogPost` SET `Blog`='0', `__timestamp__` = ".time()." WHERE `id`='".$this->id."'";
				$db->sql($sql);
				$this->row['Blog'] = 0;
			}
		}

		public function getBlog() {
			if ($this->row['Blog'] == 0) {
				return null;
			} else {
				return Blog::ROW($this->row['Blog']);
			}
		}
public function setTitle($value) { $this->row['Title'] = $value; $value = mysql_real_escape_string($value); $timestamp = time(); $sql = "UPDATE `BlogPost` SET `Title`='$value',`__timestamp__` = $timestamp, `__operation__` = 'UPDATE' WHERE `id`='{$this->id}'"; Database::getInstance()->sql($sql);} public function getTitle() { return $this->row['Title']; }

public function setDescription($value) { $this->row['Description'] = $value; $value = mysql_real_escape_string($value); $timestamp = time(); $sql = "UPDATE `BlogPost` SET `Description`='$value',`__timestamp__` = $timestamp, `__operation__` = 'UPDATE' WHERE `id`='{$this->id}'"; Database::getInstance()->sql($sql);} public function getDescription() { return $this->row['Description']; }


		public function setContent($value) {
			if (is_object($value) && $value->getClassName() == 'Document') {
				$id = $value->getId();
				$db = Database::getInstance();
				$sql = "UPDATE `BlogPost` SET `Content`='".$id."',	`__timestamp__` = ".time()." WHERE `id`='".$this->id."'";
				$db->sql($sql);
				$this->row['Content'] = $id;
			} else if ($value === null) {
				$db = Database::getInstance();
				$sql = "UPDATE `BlogPost` SET `Content`='0', `__timestamp__` = ".time()." WHERE `id`='".$this->id."'";
				$db->sql($sql);
				$this->row['Content'] = 0;
			}
		}

		public function getContent() {
			if ($this->row['Content'] == 0) {
				return null;
			} else {
				return Document::ROW($this->row['Content']);
			}
		}

		public function setComments($value) {
			if (is_object($value) && $value->getClassName() == 'Comment') {
				$id = $value->getId();
				$db = Database::getInstance();
				$sql = "UPDATE `BlogPost` SET `Comments`='".$id."',	`__timestamp__` = ".time()." WHERE `id`='".$this->id."'";
				$db->sql($sql);
				$this->row['Comments'] = $id;
			} else if ($value === null) {
				$db = Database::getInstance();
				$sql = "UPDATE `BlogPost` SET `Comments`='0', `__timestamp__` = ".time()." WHERE `id`='".$this->id."'";
				$db->sql($sql);
				$this->row['Comments'] = 0;
			}
		}

		public function getComments() {
			if ($this->row['Comments'] == 0) {
				return null;
			} else {
				return Comment::ROW($this->row['Comments']);
			}
		}
public function setTimeCreation($value) { $value = str_replace(',', '.', $value); $this->row['TimeCreation'] = $value; $value = mysql_real_escape_string($value); $timestamp = time(); $sql = "UPDATE `BlogPost` SET `TimeCreation`='$value', `__timestamp__` = $timestamp, `__operation__` = 'UPDATE'  WHERE `id`='{$this->id}'"; Database::getInstance()->sql($sql); } public function getTimeCreation() { $value = $this->row['TimeCreation']; settype($value, 'float'); return $value; }

public function setTimePublished($value) { $value = str_replace(',', '.', $value); $this->row['TimePublished'] = $value; $value = mysql_real_escape_string($value); $timestamp = time(); $sql = "UPDATE `BlogPost` SET `TimePublished`='$value', `__timestamp__` = $timestamp, `__operation__` = 'UPDATE'  WHERE `id`='{$this->id}'"; Database::getInstance()->sql($sql); } public function getTimePublished() { $value = $this->row['TimePublished']; settype($value, 'float'); return $value; }

public function setOptions($value) { $this->row['Options'] = $value; $value = mysql_real_escape_string($value); $timestamp = time(); $sql = "UPDATE `BlogPost` SET `Options`='$value',`__timestamp__` = $timestamp, `__operation__` = 'UPDATE' WHERE `id`='{$this->id}'"; Database::getInstance()->sql($sql);} public function getOptions() { return $this->row['Options']; }

public function setUrl($value) { $this->row['Url'] = $value; $value = mysql_real_escape_string($value); $timestamp = time(); $sql = "UPDATE `BlogPost` SET `Url`='$value',`__timestamp__` = $timestamp, `__operation__` = 'UPDATE' WHERE `id`='{$this->id}'"; Database::getInstance()->sql($sql);} public function getUrl() { return $this->row['Url']; }


		public function setAuthor($value) {
			if (is_object($value) && $value->getClassName() == 'SystemUser') {
				$id = $value->getId();
				$db = Database::getInstance();
				$sql = "UPDATE `BlogPost` SET `Author`='".$id."',	`__timestamp__` = ".time()." WHERE `id`='".$this->id."'";
				$db->sql($sql);
				$this->row['Author'] = $id;
			} else if ($value === null) {
				$db = Database::getInstance();
				$sql = "UPDATE `BlogPost` SET `Author`='0', `__timestamp__` = ".time()." WHERE `id`='".$this->id."'";
				$db->sql($sql);
				$this->row['Author'] = 0;
			}
		}

		public function getAuthor() {
			if ($this->row['Author'] == 0) {
				return null;
			} else {
				return SystemUser::ROW($this->row['Author']);
			}
		}

	}
